from pathlib import Path

PROJECT_DIR = Path(__file__).parent

# Path to the MediaPipe face landmark model.
MODEL_PATH = PROJECT_DIR / "models" / "face_landmarker.task"

# Which webcam to use (0 = built-in camera).
CAMERA_INDEX = 0

# At the start of each session we measure your normal open-eye Eye Aspect
# Ratio (EAR) for this many seconds, so keep your eyes open while it calibrates.
CALIBRATION_SECONDS = 2.0

# Eyes count as "closed" when EAR drops below this fraction of your open-eye EAR.
CLOSED_RATIO = 0.65

# Default for how long the eyes must stay closed before the alarm goes off
# (adjustable in the app; your choice is saved in settings.json).
CLOSED_SECONDS_BEFORE_ALARM = 5.0

# Sound played (on repeat) while the alarm is active. Generated by
# make_alarm_sound.py; any .wav/.mp3/.aiff path works here too.
ALARM_SOUND = PROJECT_DIR / "sounds" / "alarm.wav"

# Multiplier on the sound's own loudness (1 = normal). alarm.wav is already
# at max level, so going above 1 adds distortion (which is louder and harsher).
ALARM_VOLUME_BOOST = 1

# Mac output volume (0-100) forced on while the alarm plays, then restored.
# Set to None to leave your volume alone.
ALARM_SYSTEM_VOLUME = 50

# Width of the camera preview in the window, in pixels.
PREVIEW_WIDTH = 400

# Phone alerts via ntfy (https://ntfy.sh): free push notifications. Install the
# ntfy app and subscribe to the topic shown in the app's Phone alerts window.
NTFY_SERVER = "https://ntfy.sh"

# Seconds between phone notifications while the alarm is ringing. Note: the
# public ntfy.sh server allows a burst of ~60, then about 1 per 5 seconds.
PHONE_ALERT_INTERVAL = 1.0
